[build]
  # This config catches the build if Netlify is still set to the /frontend base directory
  command = "cd .. && npm install && node scripts/build-all.js"
  publish = "out"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
